---
title: "NER - Variables harmonization for all surveys and years"
author: "ganlea"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
	echo = TRUE,
	message = FALSE,
	warning = FALSE
)
```


```{r packages needed}
library(haven)
library(labelled)
library(tidyverse)
library(dplyr)
library(Hmisc)
library(gtsummary)
library(readxl)
library(foreign)
```



```{r}
rm(list = ls())
```

```{r environment settings}

chemin = "C:/Users/LENOVO/Desktop/isep3/semestre2/Projet statistique sous R/Projet Niger - Copie"
dir_input_data = paste0(chemin,"/input_data/NER")
dir_output_data = paste0(chemin,"/output_data/NER")
```

```{r read harmonization excel file}

NER_Harmonization_variables <- read_excel(paste0(dir_input_data,"/NER_Harmonization.xlsx"), 
    sheet = "variables_harmonization")
#View(NER_Harmonization_variables)

NER_Harmonization_description <- read_excel(paste0(dir_input_data,"/NER_Harmonization.xlsx"), 
    sheet = "description")
#View(NER_Harmonization_description)
```



```{r data importation}

lst_data = NER_Harmonization_description$Data
lst_test = NER_Harmonization_description$Name

for(i in 1:length(lst_data)) {                              # Head of for-loop
  chemin_fichier <- paste0(dir_input_data,"/",lst_data[i])
  
  if (file.exists(chemin_fichier)) {
    extension_fichier <- substr(lst_data[i], nchar(lst_data[i]) - 2, nchar(lst_data[i]))
    if(extension_fichier=="sav") {
      assign(lst_test[i],                 # Read and store data frames
         read_sav(paste0(dir_input_data,"/",lst_data[i])))
    }
    else if(extension_fichier=="dta")
    {
      assign(lst_test[i],                 # Read and store data frames
         read_dta(paste0(dir_input_data,"/",lst_data[i])))
    }
  
} else { 
  assign(lst_test[i],NA)
  print(lst_test[i])

  next
}
  
}
```





```{r select and rename columns needed}

for (j in 1:length(lst_test)){
         df=  get(lst_test[j], envir = .GlobalEnv)
          for (i in 1:nrow(NER_Harmonization_variables)){
            df[,NER_Harmonization_variables$NewVariable_Name[i]]=ifelse(is.na(NER_Harmonization_variables[i,lst_test[j]]),NA,df[,NER_Harmonization_variables[i,lst_test[j]][[1]]])
          }
    
    df<-df %>% select(NER_Harmonization_variables$NewVariable_Name)
    write_dta(df, paste0(dir_output_data,"/",lst_test[j],".dta"))
    
}
# niger_ea_2020
```


```{r remove final environment variables}
rm(list = ls())
```

```{r}

```



